### PR TITLE
Loosen tests

### PR DESCRIPTION
**Pull request by BridgeAR**
This is some times showing up on [citgm](https://github.com/nodejs/citgm) and to make the test fail less often, it would be nice if this would be accepted.

### CODE REVIEW

**Comment by BridgeAR** [comment]
While looking at the test result again, this will likely not resolve the issue (it took 5229 ms).

@ForbesLindesay @TimothyGu do you have another idea how to improve this properly?

**Comment by BridgeAR** [comment]
See https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/1418/nodes=aix61-ppc64/testReport/junit/(root)/citgm/thread_sleep_v2_0_0/

**Comment by ForbesLindesay** [comment]
I'm not really sure what to suggest. It shouldn't be taking 5 seconds to evaluate `node -e "setTimeout(()=>{}, 1000)"`. If it does, I think our tests **should** fail. I'd be ok with accepting your proposed change, but not with increasing the tolerance to multiple seconds.

**Comment by BridgeAR** [comment]
@ForbesLindesay I agree to that. When I opened the PR I first did not look exactly at the outcome and did not see that it took multiple seconds.

I wonder if the `timeout` option could help in some cases to prevent this from happening.

**Comment by ForbesLindesay** [comment]
Thanks @BridgeAR that's a great suggestion. Let me know if the tests still need relaxing a bit. I'm hoping they'll be fine as they are.

**Comment by BridgeAR** [comment]
Awesome, thanks. I'll let you know if something comes up.

**Pull request closed without merging**
